### ISSUE TITLE
where to locate googleads-shopping-samples/python folder ?

### ISSUE THREAD

**Issue by DhruvGupta5** [fblascogarma/google_ads_frontend#1]
I cant seem to find the mentioned folder to copy my credentials file into, any help would be great ?

**Comment by fblascogarma** [comment]
Hi Dhruv, thank you for reaching out. You can save the json file with the client_secrets anywhere you want. I updated the guide and REAMDE files to clarify this. 

You will need to save the path to that file as an environment variable to use when building the credentials to make API calls to Google Ads API.
